# Generated by Django 4.1.7 on 2023-03-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_time_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
