# Generated by Django 4.1.7 on 2023-03-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_time_pro_delete_seat_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='home.film')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=100)),
                ('sro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='home.time')),
            ],
        ),
    ]
