# Generated by Django 4.1.7 on 2023-03-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_time_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='sro',
        ),
        migrations.RemoveField(
            model_name='time',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
