# Generated by Django 4.1.7 on 2023-03-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='sro',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
